Repository jenkinsci/JenkinsPipelineUnit, pull requests merged in 2019-03, with the labels that each got.

#81 issue-80: Fix invalid code snippet in the configuration section of README.md
  README.md
Labels: bug

#95 Add procedure to analyze fail scenarios
  README.md
Labels: doc, enhancement

#66 Remove same permutation contained twice in parameterized test runner.
  src/test/groovy/com/lesfurets/jenkins/TestSharedLibrary.groovy
Labels: bug

#76 Replace loadScript with runScript in some cases
  README.md
Labels: doc
